#! /bin/bash

##############################################################################################################################
# git create-profile <username>
#
# Creates a new profile for a user
##############################################################################################################################

set -e

source functions.sh

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -u|--user)
    username="$2"
    shift 
    shift
    ;;
    -e|--email)
    email="$2"
    shift 
    shift
    ;;
    *)    
    printf ""
      printf 'Usage:'
      printf'  git create-profile [-u|--username <username>] [-e|--email <email>]'
      exit
    shift 
    ;;
esac
done

set -- "${POSITIONAL[@]}"

## Get passed parameters and request for those not passed
# Create Username
if [ -z "$username" ]; then
  printf "Creating New User \nUsername: "
  read username
else
  # Basic Setup for most users
  printf "Creating User $username...\n"
fi

while :
do

  if [ -f "$GIT_PROFILE_DIR/$username" ]; then
    printf "Username already exists. Pick another\nUsername: "
    # Username can be passed from commandline
    read username
  else
    break
  fi
done

read -p "Enter Name (user.name): " name

if [ -z "$email" ]; then
  read -p "Email (user.email): " email
fi


# Setup User Profile
printf "Setting up User Profile..."
export GIT_CONFIG="$GIT_PROFILE_DIR/$username"
git config user.name "$name"
git config user.email "$email"

update_profile $username
printf "Profile Created\nNow running as $username"
