#! /bin/bash

##############################################################################################################################
# git use-profile 
#
# sets the current profile to a user
##############################################################################################################################
set -e

usage(){
cat <<EOF
  Usage:
    git use-profile USERNAME
EOF
}

source functions.sh

if [ $# -ne 0 ]; then
  username="$1"
else
  usage
  exit 1
fi


# Convert username to lowercase
username=$(echo "$username" |tr '[:upper:]' '[:lower:]')

if [ ! -f "$GIT_PROFILE_DIR/$username" ]; then
  echo "Username $1 does not exists. Use 'git create-profile' to create it"
else
  update_profile $username
  printf "Profile Updated\nGit now running as $username"
fi
