#! /bin/bash

##############################################################################################################################
# git global-config
#
# Set add config to the global config which can be used by all profiles
##############################################################################################################################

set -e
source functions.sh

usage(){
cat <<EOF
  Usage:
    git global-config [CONFIG-OPTS]

    Example
    git global-config core.sshCommand "ssh -i /path/to/id_rsa"

EOF
}


export GIT_CONFIG="$GIT_PROFILE_DIR/global"
git config "$1"

# Update the current profile to reflect in it
get_current_profile
update_profile $username
