#! /bin/bash

##############################################################################################################################
# git remove-profile 
#
# removes a user profile
##############################################################################################################################
set -e

source functions.sh

usage(){
cat <<EOF
  Usage:
    git remove-profile [-f|--force] USERNAME
EOF
}

get_current_profile
current_user=$username

use_force=
username=


if [[ $# -gt 2 || $# -lt 1 ]]; then
  usage
  exit 2
fi

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -f|--force)
      use_force=1
      shift
    ;;
    *)
      username=$key
      shift
    ;;
esac
done

if [ -z "$username" ]; then
  usage
  exit
fi

# Convert username to lowercase
username=$(echo "$username" |tr '[:upper:]' '[:lower:]')

if [ ! -f "$GIT_PROFILE_DIR/$username" ]; then
  echo "Username $1 does not exists. Use 'git create-profile' to create it"
else
  # confirm user profile deletion
  read -p "Are you sure you want to remove $username profile? (Y/n): " REPLY
  REPLY=$(echo "$REPLY" |tr '[:upper:]' '[:lower:]')
  if [ "$REPLY" != "y" ]; then
    exit
  fi

  # IF user is current user, set config to default global config
  if [ "$username" = "$current_user" ]; then
    if [ -z "$use_force" ]; then
      echo "You cannot delete the active user. Add the -f/--force flag to force removal"
      exit 1
    else
      echo "You are deleting the active user, your Current profile will be set to global config"
      update_profile "global"
    fi
  fi

  rm "$GIT_PROFILE_DIR/$username"
  printf "Profile $username deleted"
fi
