#! /bin/bash

##############################################################################################################################
# git current-profile 
#
# Returns current profile
##############################################################################################################################
set -e

usage(){
cat <<EOF
  Usage:
    git current-profile
EOF
}

if [ $# -gt 0 ]; then
  usage
  exit
fi

source functions.sh

get_current_profile
printf "Current Profile $username"
