#! /bin/bash

##############################################################################################################################
# git create-profile 
#
# Creates a new profile for a user
##############################################################################################################################

set -e

source functions.sh

usage(){
cat <<EOF
  Usage:
    git create-profile [-u|--username USERNAME] [-n|--name NAME] [-e|--email EMAIL]
EOF
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -u|--user)
      username="$2"
      shift 
      shift
    ;;
    -n|--name)
      name="$2"
      shift 
      shift
    ;;
    -e|--email)
      email="$2"
      shift 
      shift
    ;;
    *)    
      usage
      exit
    ;;
esac
done

set -- "${POSITIONAL[@]}"

## Get passed parameters and request for those not passed
# Create Username
if [ -z "$username" ]; then
  printf "Creating New User \nUsername: "
  read username
else
  # Basic Setup for most users
  printf "Creating User $username...\n"
fi

while :
do

  if [ -f "$GIT_PROFILE_DIR/$username" ]; then
    printf "Username already exists. Pick another\nUsername: "
    # Username can be passed from commandline
    read username
  else
    break
  fi
done

if [ -z "$name" ]; then
  read -p "Enter Name (user.name): " name
fi

if [ -z "$email" ]; then
  read -p "Email (user.email): " email
fi


# Setup User Profile
printf "Setting up User Profile...\n"
export GIT_CONFIG="$GIT_PROFILE_DIR/$username"
git config user.name "$name"
git config user.email "$email"

# Convert username to lowercase
username=$(echo "$username" |tr '[:upper:]' '[:lower:]')

update_profile $username
#TODO delete user config file if creation fails using TRAP
printf "Profile Created\nGit is now running as $username\n"
