#! /bin/bash

set -e

source functions.sh

get_variables() {
  # Create Username
  if [ -z "$username" ]; then
    printf "Creating New User \nUsername: "
    read username
  else
    # Basic Setup for most users
    printf "Creating User $username...\n"
  fi

  while :
  do

    if [ -f "$GIT_PROFILE_DIR/$username" ]; then
      printf "Username already exists. Pick another\nUsername: "
      # Username can be passed from commandline
      read username
    else
      break
    fi
  done

  printf "Enter Name (user.name): "
  read name

  if [ -z "$email" ]; then
    printf "Email (user.email): "
    read email
  fi
}

setup(){
  echo "setting up user profile..."
  mkdir -p "$GIT_PROFILE_DIR"
  export GIT_CONFIG="$GIT_PROFILE_DIR/$username"
  git config user.name "$name"
  git config user.email "$email"

  #TODO store current config and restore if installation fails
  update_profile
  printf "Setup complete\nRunning as $username"
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -u|--user)
    username="$2"
    shift 
    shift
    ;;
    -e|--email)
    email="$2"
    shift 
    shift
    ;;
    *)    
    POSITIONAL+=("$1") # save it in an array for later
    shift 
    ;;
esac
done

set -- "${POSITIONAL[@]}"

get_variables
setup
